### ISSUE TITLE
Error while installation of BerryPI

### ISSUE THREAD

**Issue by disisjisha** [spichardo/BerryPI#8]
Hi all,

  While installing BerryPI , I am getting this error..

bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
./init.sh: line 187: cd: Python-2.7.4: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
./init.sh: line 189: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
rm: cannot remove 'Python-2.7.4': No such file or directory
Python 2.7 directory not found
BerryPI initialization can not continue
Aborted

Kindly help me out to solve this issue

Regards
Dr Jisha A Abraham

**Comment by rubel75** [comment]
To be honest, I never used init.sh script :)
The best way to get berrypi work is to edit manually config file. You only need to point you python installation and berrypi home directory.
Make sure you have a numpy.

I hope it will help
Oleg

**Comment by rubel75** [comment]
The current version has greatly simplified installation/configuration process. Many redundant steps are eliminated. Please, check it out.
