### ISSUE TITLE
Why this package only supports density functional all-electron package?

### ISSUE THREAD

**Issue by hongyi-zhao** [spichardo/BerryPI#9]
I noticed [the following description of this package](https://github.com/spichardo/BerryPI#readme):
```
BerryPI is a software for the calculation of Berry phase and related properties of solids
(including topological materials) with WIEN2k density functional package.
```
But I really wonder why this package only supports density functional all-electron package?

Regards,
HZ

**Comment by rubel75** [comment]
Other packages (e.g., VASP, Abinit, ....) have their internal capabilities to compute Berry phase, polarization and related properties. WIEN2k did not have that option and our group filled the gap. There is no limitation for the calculation method to favor an all-electron code vs a pseudopotential code other than possible inaccuracies of pseudopotentials.
